server:
  port: 22260
spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-sentinel-core-demo
  cloud:
    sentinel:
      datasource:
        ds1:
          zk:
            server-addr:
            path: /mi-global/sentinel-rule-config/${spring.application.name}
            rule-type: flow
        ds2:
          zk:
            server-addr:
            path: /mi-global/sentinel-rule-config/${spring.application.name}
            rule-type: degrade
      transport:
        dashboard:
      eager: true